#!/bin/sh
DAEMON=/usr/bin/glive-server
NAME=gliveserver
DESC="GLIVE Server Daemon"
ARGS="-r -d"

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -b -x $DAEMON -- $ARGS
	echo "$NAME."
	;;
    stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x $DAEMON
	echo "$NAME."
	;;
    restart)
	$0 stop
	$0 start
	;;
    reload)
	echo -n "Reloading $DESC: "
	killall -HUP $(basename ${DAEMON})
	echo "$NAME."
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
	;;
esac

exit 0
